FROM python:3.8
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
RUN mkdir /autobot
WORKDIR /autobot
COPY requirements.txt /autobot/
RUN pip install -r requirements.txt
COPY . /autobot/
